import '../styles/globals.css';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import Footer from '@/app/_components/Footer';
import Header from '@/app/_components/Header/Header';
import type { Metadata } from 'next';
import 'react-toastify/dist/ReactToastify.css';
import '@/styles/toastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Connection',
  description: 'Generated by Connection',
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <Header />
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <main className="flex-1">
          {children}
          {modal}
        </main>
        <Footer />
      </body>
    </html>
  );
}
